sudo: required
services:
  - docker

before_install:
  - docker build -t tarangs20/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run tarangs20/react-test npm test -- --coverage

after_success:
  - docker build -t tarangs20/multi-client ./client
  - docker build -t tarangs20/multi-nginx ./nginx
  - docker build -t tarangs20/multi-server ./server
  - docker build -t tarangs20/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  -docker push tarangs20/multi-client
  -docker push tarangs20/multi-nginx
  -docker push tarangs20/multi-server
  -docker push tarangs20/multi-worker
